"""
SHAP Explainer
===============
Wraps the PPO critic (value function) with a SHAP KernelExplainer
to produce per-feature attributions for each scheduling decision.

How it works:
  1. PPO predicts actions via the policy network.
  2. SHAP attributes the critic's VALUE ESTIMATE to individual features.
     (The value estimate is a scalar proxy for expected future reward.)
  3. Top-5 positive and top-5 negative drivers are extracted.
  4. These are embedded in the decision payload sent to Kafka → Grafana.

SHAP KernelExplainer:
  - Model-agnostic: works with any black-box function
  - Background dataset: 200 stratified samples from BackgroundDataGenerator
  - Explains one sample at a time (nsamples=100 for speed)
  - Each explanation call: ~50-200ms on CPU (acceptable for inference)

To avoid re-initialising on every request:
  - SHAPExplainer is a singleton loaded once by SchedulerAgent at startup
  - Background dataset is loaded from disk (pre-generated by run_shap_background.sh)

Compatible with:
  - stable-baselines3 PPO policy (MlpPolicy)
  - ai_engine/inference/scheduler_agent.py
  - ai_engine/explainability/background_generator.py
  - ai_engine/explainability/explanation_formatter.py
"""

import logging
import time
from pathlib import Path
from typing import Dict, List, Optional

import numpy as np

try:
    import shap
except ImportError:
    raise ImportError(
        "\n\nshap is not installed.\n"
        "Fix: run   pip install shap   then try again.\n"
    )

from ai_engine.explainability.background_generator import (
    FEATURE_NAMES,
    BackgroundDataGenerator,
)

logger = logging.getLogger(__name__)

_BG_PATH = Path("data/shap/background_dataset.npy")


class SHAPExplainer:
    """
    SHAP KernelExplainer wrapping the PPO critic value function.

    Usage:
        explainer = SHAPExplainer.load(model, config)
        explanation = explainer.explain(state_45dim)
    """

    def __init__(
        self,
        model,
        background: np.ndarray,
        nsamples:   int = 100,
    ):
        """
        Args:
            model:      Stable-Baselines3 PPO model (or compatible).
            background: (n, 45) float32 background dataset.
            nsamples:   SHAP samples per explanation call.
                        Higher = more accurate, slower (100 is a good default).
        """
        self._model      = model
        self._background = background
        self._nsamples   = nsamples
        self._explainer: Optional[shap.KernelExplainer] = None
        self._feature_names = FEATURE_NAMES

        self._initialise_explainer()

    # -----------------------------------------------------------------------
    # Factory
    # -----------------------------------------------------------------------

    @classmethod
    def load(
        cls,
        model,
        config:   Dict,
        nsamples: int = 100,
        force_regen: bool = False,
    ) -> "SHAPExplainer":
        """
        Loads background dataset from disk (generated by run_shap_background.sh)
        or generates it on the fly if not found.

        Args:
            model:       SB3 PPO model.
            config:      Project config dict (used by BackgroundDataGenerator).
            nsamples:    SHAP samples per explanation call.
            force_regen: If True, regenerate background dataset even if cached.

        Returns:
            Initialised SHAPExplainer ready for .explain() calls.
        """
        logger.info("SHAPExplainer: loading background dataset ...")

        generator  = BackgroundDataGenerator(config)
        background = generator.generate(
            n_samples=200,
            seed=42,
            force=force_regen,
        )

        logger.info("SHAPExplainer: background shape %s", background.shape)
        return cls(model, background, nsamples=nsamples)

    # -----------------------------------------------------------------------
    # Public
    # -----------------------------------------------------------------------

    def explain(self, state: np.ndarray) -> Dict:
        """
        Computes SHAP values for a single 45-dim state vector.

        Args:
            state: (45,) or (1, 45) float32 array.

        Returns:
            {
              "top_drivers":        [{"feature": str, "shap_value": float, "direction": str}, ...],
              "base_value":         float,
              "shap_values":        {feature_name: shap_value, ...},
              "top_positive":       [{"feature": str, "shap_value": float}, ...],  # top 5
              "top_negative":       [{"feature": str, "shap_value": float}, ...],  # top 5
              "explanation_ms":     float,
              "state_mean":         float,
              "state_std":          float,
            }
        """
        if self._explainer is None:
            logger.error("SHAPExplainer: explainer not initialised — returning empty.")
            return self._empty_explanation()

        x = np.array(state, dtype=np.float32).reshape(1, 45)

        t0 = time.perf_counter()
        try:
            shap_vals = self._explainer.shap_values(
                x,
                nsamples=self._nsamples,
                silent=True,
            )
        except Exception as exc:
            logger.error("SHAPExplainer: shap_values failed: %s", exc)
            return self._empty_explanation()

        elapsed_ms = (time.perf_counter() - t0) * 1000

        # KernelExplainer returns (1, 45) — squeeze to (45,)
        if isinstance(shap_vals, list):
            vals = np.array(shap_vals[0]).reshape(-1)
        else:
            vals = np.array(shap_vals).reshape(-1)

        base_val = float(self._explainer.expected_value)
        if isinstance(base_val, (list, np.ndarray)):
            base_val = float(np.array(base_val).flat[0])

        # Build named shap values dict
        named: Dict[str, float] = {
            name: round(float(v), 6)
            for name, v in zip(self._feature_names, vals)
        }

        # Top 5 positive drivers (features pushing value UP = good)
        sorted_vals  = sorted(named.items(), key=lambda kv: kv[1], reverse=True)
        top_positive = [
            {"feature": k, "shap_value": round(v, 6)}
            for k, v in sorted_vals[:5] if v > 0
        ]

        # Top 5 negative drivers (features pushing value DOWN = cost/risk)
        sorted_neg   = sorted(named.items(), key=lambda kv: kv[1])
        top_negative = [
            {"feature": k, "shap_value": round(v, 6)}
            for k, v in sorted_neg[:5] if v < 0
        ]

        # Combined top 5 by absolute value
        top_drivers = sorted(
            [
                {
                    "feature":    k,
                    "shap_value": round(v, 6),
                    "direction":  "positive" if v > 0 else "negative",
                }
                for k, v in named.items()
            ],
            key=lambda d: abs(d["shap_value"]),
            reverse=True,
        )[:5]

        logger.debug(
            "SHAP: %.1fms | base=%.3f | top=%s",
            elapsed_ms,
            base_val,
            top_drivers[0]["feature"] if top_drivers else "none",
        )

        return {
            "top_drivers":    top_drivers,
            "base_value":     round(base_val, 6),
            "shap_values":    named,
            "top_positive":   top_positive,
            "top_negative":   top_negative,
            "explanation_ms": round(elapsed_ms, 2),
            "state_mean":     round(float(x.mean()), 4),
            "state_std":      round(float(x.std()),  4),
        }

    def get_feature_names(self) -> List[str]:
        return list(self._feature_names)

    def get_background_shape(self) -> tuple:
        return self._background.shape

    # -----------------------------------------------------------------------
    # Private
    # -----------------------------------------------------------------------

    def _initialise_explainer(self):
        """Creates the SHAP KernelExplainer wrapping the PPO critic."""
        logger.info(
            "SHAPExplainer: initialising KernelExplainer "
            "(background=%s, nsamples=%d) ...",
            self._background.shape, self._nsamples,
        )
        t0 = time.perf_counter()

        try:
            def _critic_fn(x: np.ndarray) -> np.ndarray:
                """
                Wrapper around PPO critic value function.
                Input:  (n, 45) float32
                Output: (n,)    float32 — value estimates
                """
                import torch
                x_t  = torch.tensor(x, dtype=torch.float32)
                vals = []
                with torch.no_grad():
                    for i in range(len(x_t)):
                        obs = x_t[i].unsqueeze(0)
                        try:
                            # SB3 PPO critic value estimate
                            v = self._model.policy.predict_values(obs)
                            vals.append(float(v.item()))
                        except Exception:
                            vals.append(0.0)
                return np.array(vals, dtype=np.float32)

            self._explainer = shap.KernelExplainer(
                model=_critic_fn,
                data=self._background,
            )

            elapsed = (time.perf_counter() - t0) * 1000
            logger.info(
                "SHAPExplainer: KernelExplainer ready in %.0f ms",
                elapsed,
            )

        except Exception as exc:
            logger.error("SHAPExplainer: initialisation failed: %s", exc)
            self._explainer = None

    @staticmethod
    def _empty_explanation() -> Dict:
        return {
            "top_drivers":    [],
            "base_value":     0.0,
            "shap_values":    {},
            "top_positive":   [],
            "top_negative":   [],
            "explanation_ms": 0.0,
            "state_mean":     0.0,
            "state_std":      0.0,
            "error":          "explainer_not_ready",
        }