"""
Prometheus Metrics Registry
============================
Central definition of all Prometheus metrics for CloudOS-RL.

Metrics exposed at :9090/metrics (scraped by Prometheus, displayed in Grafana):

  COUNTERS (monotonically increasing):
    cloudos_decisions_total          - total scheduling decisions
    cloudos_alerts_total             - total alerts by kind
    cloudos_workload_events_total    - workload lifecycle events

  HISTOGRAMS (distribution of values):
    cloudos_inference_latency_seconds   - end-to-end scheduling latency
    cloudos_cost_savings_ratio          - cost savings fraction per decision
    cloudos_carbon_savings_ratio        - carbon savings fraction per decision
    cloudos_rl_reward                   - RL reward signal distribution

  GAUGES (point-in-time values):
    cloudos_pipeline_pricing_fetches_total  - pipeline health counter
    cloudos_pipeline_carbon_fetches_total   - pipeline health counter
    cloudos_pipeline_errors_total           - pipeline error counter
    cloudos_active_decisions                - decisions processed in last window
    cloudos_bridge_messages_consumed_total  - Kafka messages consumed

All metrics use labels for dimensional filtering in Grafana:
  cloud, region, instance_type, purchase_option → per-dimension breakdowns
  topic → per-Kafka-topic message counters
  kind  → per-alert-type counters

Compatible with:
  - Prometheus 2.x scrape format (text/plain; version=0.0.4)
  - Grafana 10+ dashboard queries
  - prometheus_client Python library
"""

from prometheus_client import Counter, Gauge, Histogram, CollectorRegistry, REGISTRY

# ---------------------------------------------------------------------------
# Use the default global registry so /metrics endpoint picks up all metrics
# automatically without manual registration.
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# COUNTERS
# ---------------------------------------------------------------------------

DECISIONS_TOTAL = Counter(
    name="cloudos_decisions_total",
    documentation="Total number of scheduling decisions made by the RL agent",
    labelnames=["cloud", "region", "instance_type", "purchase_option"],
)

ALERTS_TOTAL = Counter(
    name="cloudos_alerts_total",
    documentation="Total number of alerts generated by the system",
    labelnames=["kind"],
)

WORKLOAD_EVENTS_TOTAL = Counter(
    name="cloudos_workload_events_total",
    documentation="Total workload lifecycle events processed",
    labelnames=["workload_type", "event_type"],
)

BRIDGE_MESSAGES_CONSUMED = Counter(
    name="cloudos_bridge_messages_consumed_total",
    documentation="Total Kafka messages consumed by the Prometheus bridge",
    labelnames=["topic"],
)

BRIDGE_PARSE_ERRORS = Counter(
    name="cloudos_bridge_parse_errors_total",
    documentation="Total message parse failures in the bridge",
    labelnames=["topic"],
)

# ---------------------------------------------------------------------------
# HISTOGRAMS
# ---------------------------------------------------------------------------

INFERENCE_LATENCY = Histogram(
    name="cloudos_inference_latency_seconds",
    documentation="End-to-end RL scheduling inference latency in seconds",
    labelnames=["cloud"],
    buckets=(0.005, 0.010, 0.025, 0.050, 0.075, 0.100, 0.200, 0.500, 1.0, 2.0),
)

COST_SAVINGS_RATIO = Histogram(
    name="cloudos_cost_savings_ratio",
    documentation="Cost savings as a fraction of baseline (0.0–1.0) per decision",
    labelnames=["cloud", "purchase_option"],
    buckets=(0.0, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.50, 0.60, 0.70, 1.0),
)

CARBON_SAVINGS_RATIO = Histogram(
    name="cloudos_carbon_savings_ratio",
    documentation="Carbon savings as a fraction of baseline (0.0–1.0) per decision",
    labelnames=["cloud", "region"],
    buckets=(0.0, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.40, 0.50, 0.70, 1.0),
)

RL_REWARD = Histogram(
    name="cloudos_rl_reward",
    documentation="RL agent reward signal per scheduling decision",
    labelnames=["cloud"],
    buckets=(-10.0, -5.0, -2.0, -1.0, 0.0, 0.5, 1.0, 2.0, 3.0, 5.0, 7.0, 10.0),
)

ESTIMATED_COST_PER_HR = Histogram(
    name="cloudos_estimated_cost_per_hr_usd",
    documentation="Estimated cost per hour in USD for scheduled workloads",
    labelnames=["cloud", "instance_type"],
    buckets=(0.01, 0.05, 0.10, 0.25, 0.50, 1.0, 2.0, 5.0, 10.0, 50.0),
)

# ---------------------------------------------------------------------------
# GAUGES
# ---------------------------------------------------------------------------

ACTIVE_DECISIONS = Gauge(
    name="cloudos_active_decisions",
    documentation="Number of scheduling decisions processed in the last 60 seconds",
)

BRIDGE_CONSUMER_LAG = Gauge(
    name="cloudos_bridge_consumer_lag",
    documentation="Estimated Kafka consumer lag (messages behind) per topic",
    labelnames=["topic"],
)

PIPELINE_PRICING_FETCHES = Gauge(
    name="cloudos_pipeline_pricing_fetches_total",
    documentation="Total pricing pipeline fetch cycles completed",
)

PIPELINE_CARBON_FETCHES = Gauge(
    name="cloudos_pipeline_carbon_fetches_total",
    documentation="Total carbon pipeline fetch cycles completed",
)

PIPELINE_CUR_FETCHES = Gauge(
    name="cloudos_pipeline_cur_fetches_total",
    documentation="Total CUR pipeline fetch cycles completed",
)

PIPELINE_ERRORS = Gauge(
    name="cloudos_pipeline_errors_total",
    documentation="Total pipeline errors across all fetch types",
    labelnames=["type"],
)

CARBON_INTENSITY_GAUGE = Gauge(
    name="cloudos_carbon_intensity_gco2_per_kwh",
    documentation="Current carbon intensity gCO2/kWh per AWS region",
    labelnames=["region"],
)

PRICING_ON_DEMAND_GAUGE = Gauge(
    name="cloudos_pricing_on_demand_usd_per_hr",
    documentation="Current on-demand price USD/hr for m5.large per region",
    labelnames=["region"],
)

BRIDGE_UP = Gauge(
    name="cloudos_bridge_up",
    documentation="1 if the Kafka-Prometheus bridge is running, 0 otherwise",
)

LAST_DECISION_TIMESTAMP = Gauge(
    name="cloudos_last_decision_timestamp_seconds",
    documentation="Unix timestamp of the most recent scheduling decision",
)